version: '3'

services:
  frontend:
    image: docker.pkg.github.com/taliamax/uosu-petition/upetition-frontend:latest
    env_file:
      - "../.env"
    networks:
      - router
  backend:
    image: docker.pkg.github.com/taliamax/uosu-petition/upetition-backend:latest
    env_file:
      - "../.flaskenv"
    networks:
      - router

networks:
  router:
    external:
      name: router_router
